/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
#include <stdio.h>
#include <Android/log.h>
/* Header for class com_android_myapplication_nativeutils_JniSurface */

#ifndef _Included_com_android_myapplication_nativeutils_JniSurface
#define _Included_com_android_myapplication_nativeutils_JniSurface
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_android_myapplication_nativeutils_JniSurface
 * Method:    init
 * Signature: (Lcom/android/myapplication/SurfaceUtils;)V
 */
JNIEXPORT void JNICALL Java_com_android_myapplication_nativeutils_JniSurface_init
  (JNIEnv *, jclass, jobject);

/*
 * Class:     com_android_myapplication_nativeutils_JniSurface
 * Method:    release
 * Signature: (Lcom/android/myapplication/SurfaceUtils;)V
 */
JNIEXPORT void JNICALL Java_com_android_myapplication_nativeutils_JniSurface_release
  (JNIEnv *, jclass, jobject);

/*
 * Class:     com_android_myapplication_nativeutils_JniSurface
 * Method:    render
 * Signature: (Lcom/android/myapplication/SurfaceUtils;[III)V
 */
JNIEXPORT void JNICALL Java_com_android_myapplication_nativeutils_JniSurface_render
  (JNIEnv *, jclass, jobject, uint8_t* , jint, jint);

#ifdef __cplusplus
}
#endif
#endif
